# Generated by Django 3.2.3 on 2021-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=256)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('can_create_projects', models.BooleanField(default=False)),
            ],
        ),
    ]
