# Generated by Django 3.2.3 on 2021-06-03 10:36

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.label')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(default='', max_length=256, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', help_text='Project description', null=True)),
                ('instructions', models.TextField(blank=True, default='', help_text='Project instructions', null=True)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time of project creation')),
                ('users_can_see_other_queues', models.BooleanField(default=False)),
                ('project_type', enumchoicefield.fields.EnumChoiceField(default=projects.models.Project_type(1), enum_class=projects.models.Project_type, max_length=5)),
                ('annotators', models.ManyToManyField(blank=True, related_name='project_annotator', to='users.User')),
                ('labels', models.ManyToManyField(to='projects.Label')),
                ('managers', models.ManyToManyField(blank=True, related_name='project_manager', to='users.User')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='project_reviewer', to='users.User')),
            ],
        ),
    ]
