# Generated by Django 3.2.3 on 2021-06-03 10:41

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import tasks.models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('url', url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True)),
                ('extra', models.JSONField(blank=True, default=None, null=True)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=tasks.models.Status(2), enum_class=tasks.models.Status, max_length=9)),
                ('review_status', enumchoicefield.fields.EnumChoiceField(default=tasks.models.Review_status(1), enum_class=tasks.models.Review_status, max_length=10)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='task_annotators', to='users.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
