# Generated by Django 3.2.3 on 2021-06-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time of annotation creation')),
                ('updated_at', models.DateTimeField(help_text='Date and time of update')),
                ('result', models.JSONField()),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time of a review')),
                ('rejected_by_user', models.BooleanField(default=False)),
                ('hidden_by_user', models.BooleanField(default=False)),
                ('comment', models.ManyToManyField(blank=True, related_name='annotation_comment', to='annotations.Comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_reviewer', to='users.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_user', to='users.user')),
            ],
        ),
    ]
