# Generated by Django 3.2.3 on 2021-06-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_alter_annotation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of a review', null=True),
        ),
    ]
